# Generated by Django 6.0.6 on 2026-06-16 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourpackage",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload an optional MP4 promo video",
                null=True,
                upload_to="package_videos/",
            ),
        ),
        migrations.CreateModel(
            name="PackageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="package_gallery/")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="tours.tourpackage",
                    ),
                ),
            ],
        ),
    ]
